# Generated by Django 3.0.6 on 2020-05-25 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalmgmt', '0002_pateientpresciption'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientBill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disease', models.CharField(max_length=50)),
                ('amount', models.IntegerField()),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospitalmgmt.Patient')),
            ],
        ),
    ]
